// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1702068842;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'pushstr_rust',
    ioDirectory: '../pushstr_rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  void crateApiClearReturnedEventsCache();

  Uint8List crateApiDecryptMedia({required String descriptorJson, required String senderPubkey, String? myNsec});

  MediaDescriptor crateApiEncryptMedia({
    required List<int> bytes,
    required String recipient,
    required String mime,
    String? filename,
  });

  String crateApiFetchRecentDms({required BigInt limit, required BigInt sinceTimestamp});

  String crateApiGenerateNewKey();

  String crateApiGetNpub();

  String crateApiGetNsec();

  String crateApiHexToNpub({required String hex});

  String crateApiInitNostr({required String nsec});

  String crateApiNpubToHex({required String npub});

  String crateApiSendDm({required String recipient, required String message});

  String crateApiSendGiftDm({required String recipient, required String content, required bool useNip44});

  String crateApiUnwrapGift({required String giftJson, String? myNsec});

  String crateApiWaitForNewDms({required BigInt timeoutSecs});

  String crateApiWrapGift({required String innerJson, required String recipient, required bool useNip44});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiClearReturnedEventsCache() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiClearReturnedEventsCacheConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearReturnedEventsCacheConstMeta =>
      const TaskConstMeta(debugName: "clear_returned_events_cache", argNames: []);

  @override
  Uint8List crateApiDecryptMedia({required String descriptorJson, required String senderPubkey, String? myNsec}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(descriptorJson, serializer);
          sse_encode_String(senderPubkey, serializer);
          sse_encode_opt_String(myNsec, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDecryptMediaConstMeta,
        argValues: [descriptorJson, senderPubkey, myNsec],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecryptMediaConstMeta =>
      const TaskConstMeta(debugName: "decrypt_media", argNames: ["descriptorJson", "senderPubkey", "myNsec"]);

  @override
  MediaDescriptor crateApiEncryptMedia({
    required List<int> bytes,
    required String recipient,
    required String mime,
    String? filename,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(recipient, serializer);
          sse_encode_String(mime, serializer);
          sse_encode_opt_String(filename, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_media_descriptor, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiEncryptMediaConstMeta,
        argValues: [bytes, recipient, mime, filename],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptMediaConstMeta =>
      const TaskConstMeta(debugName: "encrypt_media", argNames: ["bytes", "recipient", "mime", "filename"]);

  @override
  String crateApiFetchRecentDms({required BigInt limit, required BigInt sinceTimestamp}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(limit, serializer);
          sse_encode_u_64(sinceTimestamp, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiFetchRecentDmsConstMeta,
        argValues: [limit, sinceTimestamp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchRecentDmsConstMeta =>
      const TaskConstMeta(debugName: "fetch_recent_dms", argNames: ["limit", "sinceTimestamp"]);

  @override
  String crateApiGenerateNewKey() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiGenerateNewKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateNewKeyConstMeta =>
      const TaskConstMeta(debugName: "generate_new_key", argNames: []);

  @override
  String crateApiGetNpub() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiGetNpubConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetNpubConstMeta => const TaskConstMeta(debugName: "get_npub", argNames: []);

  @override
  String crateApiGetNsec() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiGetNsecConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetNsecConstMeta => const TaskConstMeta(debugName: "get_nsec", argNames: []);

  @override
  String crateApiHexToNpub({required String hex}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiHexToNpubConstMeta,
        argValues: [hex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHexToNpubConstMeta => const TaskConstMeta(debugName: "hex_to_npub", argNames: ["hex"]);

  @override
  String crateApiInitNostr({required String nsec}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nsec, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiInitNostrConstMeta,
        argValues: [nsec],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitNostrConstMeta => const TaskConstMeta(debugName: "init_nostr", argNames: ["nsec"]);

  @override
  String crateApiNpubToHex({required String npub}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(npub, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiNpubToHexConstMeta,
        argValues: [npub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNpubToHexConstMeta => const TaskConstMeta(debugName: "npub_to_hex", argNames: ["npub"]);

  @override
  String crateApiSendDm({required String recipient, required String message}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(recipient, serializer);
          sse_encode_String(message, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiSendDmConstMeta,
        argValues: [recipient, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendDmConstMeta =>
      const TaskConstMeta(debugName: "send_dm", argNames: ["recipient", "message"]);

  @override
  String crateApiSendGiftDm({required String recipient, required String content, required bool useNip44}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(recipient, serializer);
          sse_encode_String(content, serializer);
          sse_encode_bool(useNip44, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiSendGiftDmConstMeta,
        argValues: [recipient, content, useNip44],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendGiftDmConstMeta =>
      const TaskConstMeta(debugName: "send_gift_dm", argNames: ["recipient", "content", "useNip44"]);

  @override
  String crateApiUnwrapGift({required String giftJson, String? myNsec}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(giftJson, serializer);
          sse_encode_opt_String(myNsec, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiUnwrapGiftConstMeta,
        argValues: [giftJson, myNsec],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUnwrapGiftConstMeta =>
      const TaskConstMeta(debugName: "unwrap_gift", argNames: ["giftJson", "myNsec"]);

  @override
  String crateApiWaitForNewDms({required BigInt timeoutSecs}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(timeoutSecs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiWaitForNewDmsConstMeta,
        argValues: [timeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaitForNewDmsConstMeta =>
      const TaskConstMeta(debugName: "wait_for_new_dms", argNames: ["timeoutSecs"]);

  @override
  String crateApiWrapGift({required String innerJson, required String recipient, required bool useNip44}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(innerJson, serializer);
          sse_encode_String(recipient, serializer);
          sse_encode_bool(useNip44, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: sse_decode_AnyhowException),
        constMeta: kCrateApiWrapGiftConstMeta,
        argValues: [innerJson, recipient, useNip44],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWrapGiftConstMeta =>
      const TaskConstMeta(debugName: "wrap_gift", argNames: ["innerJson", "recipient", "useNip44"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaDescriptor dco_decode_media_descriptor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8) throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MediaDescriptor(
      url: dco_decode_String(arr[0]),
      iv: dco_decode_String(arr[1]),
      sha256: dco_decode_String(arr[2]),
      cipherSha256: dco_decode_String(arr[3]),
      mime: dco_decode_String(arr[4]),
      size: dco_decode_usize(arr[5]),
      encryption: dco_decode_String(arr[6]),
      filename: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaDescriptor sse_decode_media_descriptor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_iv = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    var var_cipherSha256 = sse_decode_String(deserializer);
    var var_mime = sse_decode_String(deserializer);
    var var_size = sse_decode_usize(deserializer);
    var var_encryption = sse_decode_String(deserializer);
    var var_filename = sse_decode_opt_String(deserializer);
    return MediaDescriptor(
      url: var_url,
      iv: var_iv,
      sha256: var_sha256,
      cipherSha256: var_cipherSha256,
      mime: var_mime,
      size: var_size,
      encryption: var_encryption,
      filename: var_filename,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_descriptor(MediaDescriptor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.iv, serializer);
    sse_encode_String(self.sha256, serializer);
    sse_encode_String(self.cipherSha256, serializer);
    sse_encode_String(self.mime, serializer);
    sse_encode_usize(self.size, serializer);
    sse_encode_String(self.encryption, serializer);
    sse_encode_opt_String(self.filename, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
